In [1]:
import numpy as np

In [9]:
a=np.array([100,65,52,80,25,76,43,34,98,87,76,65,54,43,32,76,73,57,63,40])

In [10]:
# create array for distinction students >=70
dist = a[a>=70]
print(dist)

[100  80  76  98  87  76  76  73]


In [11]:
# create array for failed students <40
fail = a[a<40]
print(fail)

[25 34 32]


In [12]:
# create array for students having first class >=60 and <70
first = a[(a>=60) & (a<=70)]
print(first)

[65 65 63]


In [13]:
# create an array with 20 random nos from 1 to 50 and replace all even nos with -1
r=np.random.randint(1,50,20)
print(r)

[32 48  9 13 13 44 27 44 27 36  9 28 45 20 37 44 49 15 13 24]


In [14]:
r[r%2 == 0] = -1
print(r)

[-1 -1  9 13 13 -1 27 -1 27 -1  9 -1 45 -1 37 -1 49 15 13 -1]
